config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :projects, path: '/' do
    resources :tasks do
      member do
        patch 'checkout'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :name, presence: true

  before_save do
    self.checked = false if checked.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable

  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_project, only: %I[edit update destroy]
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.order(created_at: :desc)
    @project = current_user.projects.new
  end

  def edit
    respond_to do |format|
      format.js
      format.json { render json: @project, status: 200 }
    end
  end

  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.js
        format.json { render json: @project, status: 200 }
      else
        format.json { render json: @project.errors.messages, status: 422 }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.js
        format.json { render json: @project, status: 200 }
      else
        format.json { render json: @project.errors.messages, status: 422 }
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.js
      format.json { render json: @project, status: 200 }
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def require_project
    @project = current_user.projects.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_task, only: %I[edit update destroy checkout]

  def edit
    respond_to do |format|
      format.js
      format.json { render json: @task, status: 200 }
    end
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = params[:project_id]

    respond_to do |format|
      if @task.save
        format.js
        format.json { render json: @task, status: 200 }
      else
        format.json { render json: @task.errors.messages, status: 422 }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.js
        format.json { render json: @task, status: 200 }
      else
        format.json { render json: @task.errors.messages, status: 422 }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.js
      format.json { render json: @task, status: 200 }
    end
  end

  def checkout
    @task.update_attributes(checked: !@task.checked)

    respond_to do |format|
      format.js
      format.json { render json: @task, status: 200 }
    end
  end

  private

  def require_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :project_id, :expires)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_action_url(project, task)
    return project_task_url(project, task) if params[:action] == 'edit'

    project_tasks_url(project)
  end
end

app/views/layouts/_header.html.erb
<header class="header bg-white shadow-sm">
  <div class="container py-2">
    <div class="d-flex justify-content-end">
      <% if user_signed_in? %>
        <div class="dropdown show">
          <a class="btn btn-secondary rounded-0 shadow-sm dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
            <%= current_user.email %>
          </a>

          <div class="dropdown-menu">
            <%= link_to "Projects", projects_url, class: 'dropdown-item' %>
            <%= link_to "Settings", edit_user_registration_url, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_url, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
      <% else %>
        <nav class="nav">
          <%= link_to "Log In", new_user_session_url, class: 'nav-link' %>
          <%= link_to "Sign Up", new_user_registration_url, class: 'nav-link' %>
        </nav>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/99b691cb27.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="min-vh-100">
    <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, html: { class: 'project__form form-inline align-items-start', autocomplete: 'off' }) do |f| %>
  <div>
    <%= f.text_field :name,
      placeholder: 'Name',
      class: 'form-control form__text-input rounded-0 px-0' %>
    <div class="form__error-message small"></div>
  </div>
  <%= f.submit class: 'btn btn-success rounded-0 shadow-sm ml-sm-3 mt-3 mt-sm-0' %>
<% end %>

app/views/projects/_project.html.erb
<div class="project bg-white shadow-sm mt-3">
  <div class="d-flex justify-content-between align-items-center px-4 py-2">
    <div class="project__form-container d-none">
    </div>
    <div class="project__title font-weight-bold text-truncate">
      <%= project.name %>
    </div>
    <div class="d-flex">
      <%= link_to edit_project_url(project),
        class: 'action-button project__edit-button p-2',
        remote: true do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to project,
        method: :delete,
        class: 'action-button project__delete-button p-2',
        remote: true do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
  <div class="tasks border-top">
    <div class="d-flex px-4 py-2">
      <%= render "tasks/form", task: Task.new, project: project %>
    </div>
    <%= render project.tasks.order(created_at: :asc) %>
  </div>
</div>

app/views/projects/create.js.erb
$('.project__form').off('ajax:success').bind('ajax:success', function() {
  $('.projects').prepend("<%= j render @project %>");
});

app/views/projects/destroy.js.erb
$('.project__delete-button').off('ajax:success').bind('ajax:success', function() {
  const project = $(this).parents('.project');

  project.fadeOut(300, () => project.remove());
});

app/views/projects/edit.js.erb
$('.project__edit-button').off('ajax:success').bind('ajax:success', function() {
  const container = $(this).parents('.project').find('.project__form-container');
  $(container).toggleClass('d-none');
  $(this).parents('.project').find('.project__title').toggleClass('d-none');

  container.html("<%= j render "form", project: @project %>");
});

app/views/projects/index.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="bg-white shadow-sm px-4 py-2">
        <%= render "form", project: @project %>
      </div>
      <div class="projects d-flex flex-column">
        <%= render @projects %>
      </div>
    </div>
  </div>
</div>

app/views/projects/update.js.erb
$('.project__form').off('ajax:success').bind('ajax:success', function() {
  const container = $(this).parents('.project').find('.project__title');

  container.html("<%= j @project.name %>");
});

app/views/tasks/_checkbox.html.erb
<%= check_box_tag :checked, task.checked, task.checked, data: { 'remote': 'true', 'url': checkout_project_task_url(task.project, task), 'method': 'patch' }, class: 'task__checkbox d-block' %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: task_action_url(project, task), html: { class: 'task__form form-inline align-items-start', autocomplete: 'off' }) do |f| %>
  <div>
    <%= f.text_field :name,
      placeholder: 'Name',
      class: 'form-control form__text-input rounded-0 px-0' %>
    <div class="form__error-message small"></div>
  </div>
  <%= f.date_field :expires, class: 'form-control form__date-input rounded-0 px-0 ml-sm-3 position-relative' %>
  <%= f.submit class: 'btn btn-success rounded-0 shadow-sm ml-sm-3 mt-3 mt-sm-0' %>
<% end %>

app/views/tasks/_task.html.erb
<div class="task">
  <div class="d-flex justify-content-between align-items-center px-4 py-2">
    <div class="d-flex align-items-center">
      <div class="task__form-container d-none">
      </div>
      <div class="task__checkbox">
        <%= render 'tasks/checkbox', task: task %>
      </div>
      <div class="task__title ml-3 text-truncate">
        <%= task.name %>
      </div>
    </div>
    <div class="d-flex align-items-center">
      <p class="task__expire-date small mb-0 mr-3 text-muted">
        <%= task&.expires %>
      </p>
      <%= link_to edit_project_task_url(task.project, task),
        class: 'action-button task__edit-button p-2',
        remote: true do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to project_task_url(task.project, task),
        method: :delete,
        class: 'action-button task__delete-button p-2',
        remote: true do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/checkout.js.erb
$('.task__checkbox').off('ajax:success').bind('ajax:success', function() {
  const container = $(this).parent()

  container.find('.task__checkbox').remove()
  container.prepend("<%= j render 'tasks/checkbox', task: @task %>")
});

app/views/tasks/create.js.erb
$('.task__form').off('ajax:success').bind('ajax:success', function() {
  const project = $(this).parents('.project')

  project.find('.tasks').append("<%= j render @task %>")
});

app/views/tasks/destroy.js.erb
$('.task__delete-button').off('ajax:success').bind('ajax:success', function() {
  const task = $(this).parents('.task');

  task.fadeOut(300, () => task.remove());
});

app/views/tasks/edit.js.erb
$('.task__edit-button').off('ajax:success').bind('ajax:success', function() {
  const task = $(this).parents('.task');

  task.find('.task__checkbox').toggleClass('d-none');
  task.find('.task__title').toggleClass('d-none');

  task.find('.task__form-container').toggleClass('d-none');
  task.find('.task__form-container').html("<%= j render "tasks/form", project: @task.project, task: @task %>")
});

app/views/tasks/update.js.erb
$('.task__form').off('ajax:success').bind('ajax:success', function() {
  const task = $(this).parents('.task');

  task.find('.task__title').html("<%=  @task.name %>")
  task.find('.task__expire-date').html("<%= @task&.expires %>")
});